// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable no-irregular-whitespace, @typescript-eslint/ban-types -- auto-generated by typesafe-i18n */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 启​用
		 */
		enabled: string
		/**
		 * 开​启​或​关​闭​此​工​具
		 */
		enabledDesc: string
		/**
		 * 此​工​具​暂​无​可​配​置​项
		 */
		noConfig: string
		/**
		 * 添​加
		 */
		add: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 重​置
		 */
		reset: string
		/**
		 * 上​移
		 */
		moveUp: string
		/**
		 * 下​移
		 */
		moveDown: string
	}
	settings: {
		folder_templates: {
			/**
			 * 文​件​夹​模​板
			 */
			name: string
			/**
			 * 在​指​定​文​件​夹​下​创​建​新​文​件​时​，​无​感​知​应​用​模​板
			 */
			desc: string
			templatesFolderPath: {
				/**
				 * 模​板​文​件​夹​位​置
				 */
				name: string
				/**
				 * 存​放​模​板​文​件​的​文​件​夹​；​留​空​时​跟​随​官​方​模​板​插​件​配​置
				 */
				desc: string
			}
			rules: {
				/**
				 * 模​板​规​则
				 */
				name: string
				/**
				 * 新​规​则
				 */
				unnamed: string
				/**
				 * 开​启​或​关​闭​此​规​则
				 */
				enabledDesc: string
				/**
				 * 创​建​第​一​条​规​则
				 */
				addFirst: string
				/**
				 * 个​条​件
				 */
				scopesUnit: string
				/**
				 * 此​规​则​未​设​置​模​板​文​件
				 */
				warnNoTemplate: string
				/**
				 * 预​览​：
				 */
				renamePreview: string
				templateFile: {
					/**
					 * 模​板​文​件
					 */
					name: string
					/**
					 * 命​中​规​则​后​应​用​的​模​板​；​支​持​日​期​、​时​间​等​变​量​表​达​式
					 */
					desc: string
				}
				applyMode: {
					/**
					 * 应​用​方​式
					 */
					name: string
					/**
					 * 文​件​已​有​内​容​时​的​处​理​策​略
					 */
					desc: string
					/**
					 * 仅​空​文​件
					 */
					emptyOnly: string
					/**
					 * 插​入​到​开​头
					 */
					prepend: string
				}
				renameFormat: {
					/**
					 * 重​命​名​模​板
					 */
					name: string
					/**
					 * 创​建​时​按​模​板​重​命​名​文​件​，​支​持​变​量​表​达​式​；​留​空​表​示​不​重​命​名
					 */
					desc: string
				}
			}
			scopes: {
				/**
				 * 匹​配​条​件
				 */
				name: string
				/**
				 * 无​匹​配​条​件​时​规​则​不​会​生​效
				 */
				empty: string
				/**
				 * 文​件​夹
				 */
				typeFolder: string
				/**
				 * 排​除​文​件​夹
				 */
				typeExcludeFolder: string
				/**
				 * 文​件​名​正​则
				 */
				typeFilenamePattern: string
				/**
				 * 根​目​录
				 */
				typeRoot: string
				/**
				 * f​o​l​d​e​r​/​p​a​t​h
				 */
				pathPlaceholder: string
				/**
				 * ^​\​d​+​-​\​d​+
				 */
				patternPlaceholder: string
				/**
				 * 无​效​的​正​则​表​达​式
				 */
				patternInvalid: string
				/**
				 * 包​含​子​文​件​夹
				 */
				includeSubfolders: string
			}
			variables: {
				/**
				 * 可​用​变​量
				 */
				title: string
				/**
				 * 仍​兼​容​旧​版​ ​{​d​a​t​e​}​ ​/​ ​{​t​i​m​e​}​ ​语​法​。
				 * @param {unknown} date
				 * @param {unknown} time
				 */
				legacy: RequiredParams<'date' | 'time'>
				/**
				 * 点​击​复​制
				 */
				clickToCopy: string
				/**
				 * 已​复​制
				 */
				copied: string
				/**
				 * 笔​记​名
				 */
				notename: string
				/**
				 * 上​级​文​件​夹​名
				 */
				folder: string
				/**
				 * 上​级​文​件​夹​路​径
				 */
				folderPath: string
				/**
				 * 当​前​日​期​（​Y​Y​Y​Y​-​M​M​-​D​D​）
				 */
				date: string
				/**
				 * 当​前​时​间​（​H​H​:​m​m​）
				 */
				time: string
				/**
				 * 当​前​年​份
				 */
				year: string
				/**
				 * 年​月​（​Y​Y​Y​Y​M​M​）
				 */
				yearMonth: string
				/**
				 * 毫​秒​时​间​戳
				 */
				timestamp: string
				/**
				 * 自​定​义​ ​m​o​m​e​n​t​ ​格​式
				 */
				now: string
				/**
				 * f​r​o​n​t​m​a​t​t​e​r​ ​字​段​值
				 */
				frontmatter: string
			}
		}
		quick_path: {
			/**
			 * 快​速​路​径
			 */
			name: string
			/**
			 * 快​速​获​取​指​定​文​件​/​文​件​夹​的​路​径
			 */
			desc: string
			addEditorMenu: {
				/**
				 * 添​加​编​辑​器​菜​单
				 */
				name: string
				/**
				 * 在​编​辑​器​菜​单​中​添​加​粘​贴​当​前​文​件​路​径​的​选​项
				 */
				desc: string
			}
			addFileMenu: {
				/**
				 * 添​加​文​件​列​表​菜​单
				 */
				name: string
				/**
				 * 在​文​件​列​表​菜​单​中​添​加​复​制​文​件​/​文​件​夹​路​径​的​选​项
				 */
				desc: string
			}
			useAbsolutePath: {
				/**
				 * 绝​对​路​径
				 */
				name: string
				/**
				 * 使​用​绝​对​路​径​，​即​从​操​作​系​统​根​目​录​开​始​的​路​径
				 */
				desc: string
			}
			pathSeparator: {
				/**
				 * 分​隔​符
				 */
				name: string
				/**
				 * 多​个​路​径​的​分​隔​符
				 */
				desc: string
				/**
				 * 换​行
				 */
				newline: string
				/**
				 * 逗​号
				 */
				comma: string
				/**
				 * 分​号
				 */
				semicolon: string
				/**
				 * 空​格
				 */
				space: string
			}
		}
	}
	command: {
		quick_path: {
			/**
			 * 复​制​当​前​文​件​路​径
			 */
			copy_current_file_path: string
			/**
			 * 复​制​当​前​目​录​路​径
			 */
			copy_current_folder_path: string
		}
	}
	menu: {
		quick_path: {
			/**
			 * 复​制​文​件​路​径
			 */
			copy_file_path: string
			/**
			 * 复​制​多​个​路​径
			 */
			copy_files_path: string
			/**
			 * 复​制​目​录​路​径
			 */
			copy_folder_path: string
			/**
			 * 粘​贴​当​前​文​件​路​径
			 */
			paste_current_file_path: string
			/**
			 * 粘​贴​当​前​目​录​路​径
			 */
			paste_current_folder_path: string
		}
	}
	notice: {
		quick_path: {
			/**
			 * 路​径​已​复​制​到​剪​贴​板
			 */
			copy_success: string
			/**
			 * 复​制​路​径​失​败
			 */
			copy_failure: string
			/**
			 * 当​前​文​件​位​于​根​目​录​，​无​法​获​取​上​级​文​件​夹​路​径
			 */
			root_path_warning: string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 启用
		 */
		enabled: () => LocalizedString
		/**
		 * 开启或关闭此工具
		 */
		enabledDesc: () => LocalizedString
		/**
		 * 此工具暂无可配置项
		 */
		noConfig: () => LocalizedString
		/**
		 * 添加
		 */
		add: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 重置
		 */
		reset: () => LocalizedString
		/**
		 * 上移
		 */
		moveUp: () => LocalizedString
		/**
		 * 下移
		 */
		moveDown: () => LocalizedString
	}
	settings: {
		folder_templates: {
			/**
			 * 文件夹模板
			 */
			name: () => LocalizedString
			/**
			 * 在指定文件夹下创建新文件时，无感知应用模板
			 */
			desc: () => LocalizedString
			templatesFolderPath: {
				/**
				 * 模板文件夹位置
				 */
				name: () => LocalizedString
				/**
				 * 存放模板文件的文件夹；留空时跟随官方模板插件配置
				 */
				desc: () => LocalizedString
			}
			rules: {
				/**
				 * 模板规则
				 */
				name: () => LocalizedString
				/**
				 * 新规则
				 */
				unnamed: () => LocalizedString
				/**
				 * 开启或关闭此规则
				 */
				enabledDesc: () => LocalizedString
				/**
				 * 创建第一条规则
				 */
				addFirst: () => LocalizedString
				/**
				 * 个条件
				 */
				scopesUnit: () => LocalizedString
				/**
				 * 此规则未设置模板文件
				 */
				warnNoTemplate: () => LocalizedString
				/**
				 * 预览：
				 */
				renamePreview: () => LocalizedString
				templateFile: {
					/**
					 * 模板文件
					 */
					name: () => LocalizedString
					/**
					 * 命中规则后应用的模板；支持日期、时间等变量表达式
					 */
					desc: () => LocalizedString
				}
				applyMode: {
					/**
					 * 应用方式
					 */
					name: () => LocalizedString
					/**
					 * 文件已有内容时的处理策略
					 */
					desc: () => LocalizedString
					/**
					 * 仅空文件
					 */
					emptyOnly: () => LocalizedString
					/**
					 * 插入到开头
					 */
					prepend: () => LocalizedString
				}
				renameFormat: {
					/**
					 * 重命名模板
					 */
					name: () => LocalizedString
					/**
					 * 创建时按模板重命名文件，支持变量表达式；留空表示不重命名
					 */
					desc: () => LocalizedString
				}
			}
			scopes: {
				/**
				 * 匹配条件
				 */
				name: () => LocalizedString
				/**
				 * 无匹配条件时规则不会生效
				 */
				empty: () => LocalizedString
				/**
				 * 文件夹
				 */
				typeFolder: () => LocalizedString
				/**
				 * 排除文件夹
				 */
				typeExcludeFolder: () => LocalizedString
				/**
				 * 文件名正则
				 */
				typeFilenamePattern: () => LocalizedString
				/**
				 * 根目录
				 */
				typeRoot: () => LocalizedString
				/**
				 * folder/path
				 */
				pathPlaceholder: () => LocalizedString
				/**
				 * ^\d+-\d+
				 */
				patternPlaceholder: () => LocalizedString
				/**
				 * 无效的正则表达式
				 */
				patternInvalid: () => LocalizedString
				/**
				 * 包含子文件夹
				 */
				includeSubfolders: () => LocalizedString
			}
			variables: {
				/**
				 * 可用变量
				 */
				title: () => LocalizedString
				/**
				 * 仍兼容旧版 {date} / {time} 语法。
				 */
				legacy: (arg: { date: unknown, time: unknown }) => LocalizedString
				/**
				 * 点击复制
				 */
				clickToCopy: () => LocalizedString
				/**
				 * 已复制
				 */
				copied: () => LocalizedString
				/**
				 * 笔记名
				 */
				notename: () => LocalizedString
				/**
				 * 上级文件夹名
				 */
				folder: () => LocalizedString
				/**
				 * 上级文件夹路径
				 */
				folderPath: () => LocalizedString
				/**
				 * 当前日期（YYYY-MM-DD）
				 */
				date: () => LocalizedString
				/**
				 * 当前时间（HH:mm）
				 */
				time: () => LocalizedString
				/**
				 * 当前年份
				 */
				year: () => LocalizedString
				/**
				 * 年月（YYYYMM）
				 */
				yearMonth: () => LocalizedString
				/**
				 * 毫秒时间戳
				 */
				timestamp: () => LocalizedString
				/**
				 * 自定义 moment 格式
				 */
				now: () => LocalizedString
				/**
				 * frontmatter 字段值
				 */
				frontmatter: () => LocalizedString
			}
		}
		quick_path: {
			/**
			 * 快速路径
			 */
			name: () => LocalizedString
			/**
			 * 快速获取指定文件/文件夹的路径
			 */
			desc: () => LocalizedString
			addEditorMenu: {
				/**
				 * 添加编辑器菜单
				 */
				name: () => LocalizedString
				/**
				 * 在编辑器菜单中添加粘贴当前文件路径的选项
				 */
				desc: () => LocalizedString
			}
			addFileMenu: {
				/**
				 * 添加文件列表菜单
				 */
				name: () => LocalizedString
				/**
				 * 在文件列表菜单中添加复制文件/文件夹路径的选项
				 */
				desc: () => LocalizedString
			}
			useAbsolutePath: {
				/**
				 * 绝对路径
				 */
				name: () => LocalizedString
				/**
				 * 使用绝对路径，即从操作系统根目录开始的路径
				 */
				desc: () => LocalizedString
			}
			pathSeparator: {
				/**
				 * 分隔符
				 */
				name: () => LocalizedString
				/**
				 * 多个路径的分隔符
				 */
				desc: () => LocalizedString
				/**
				 * 换行
				 */
				newline: () => LocalizedString
				/**
				 * 逗号
				 */
				comma: () => LocalizedString
				/**
				 * 分号
				 */
				semicolon: () => LocalizedString
				/**
				 * 空格
				 */
				space: () => LocalizedString
			}
		}
	}
	command: {
		quick_path: {
			/**
			 * 复制当前文件路径
			 */
			copy_current_file_path: () => LocalizedString
			/**
			 * 复制当前目录路径
			 */
			copy_current_folder_path: () => LocalizedString
		}
	}
	menu: {
		quick_path: {
			/**
			 * 复制文件路径
			 */
			copy_file_path: () => LocalizedString
			/**
			 * 复制多个路径
			 */
			copy_files_path: () => LocalizedString
			/**
			 * 复制目录路径
			 */
			copy_folder_path: () => LocalizedString
			/**
			 * 粘贴当前文件路径
			 */
			paste_current_file_path: () => LocalizedString
			/**
			 * 粘贴当前目录路径
			 */
			paste_current_folder_path: () => LocalizedString
		}
	}
	notice: {
		quick_path: {
			/**
			 * 路径已复制到剪贴板
			 */
			copy_success: () => LocalizedString
			/**
			 * 复制路径失败
			 */
			copy_failure: () => LocalizedString
			/**
			 * 当前文件位于根目录，无法获取上级文件夹路径
			 */
			root_path_warning: () => LocalizedString
		}
	}
}

export type Formatters = {}
