// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		folder_templates: {
			/**
			 * 文​件​夹​模​板
			 */
			name: string
			/**
			 * 在​指​定​文​件​夹​下​创​建​新​文​件​时​，​无​感​知​应​用​模​板
			 */
			desc: string
			templatesFolderPath: {
				/**
				 * 模​板​文​件​夹​位​置
				 */
				name: string
				/**
				 * 存​放​模​板​文​件​的​文​件​夹​,​ ​默​认​与​官​方​模​板​位​置​相​同
				 */
				desc: string
			}
			ignoredFolders: {
				/**
				 * 忽​略​文​件​夹
				 */
				name: string
				/**
				 * 在​这​些​文​件​夹​（​包​括​子​文​件​夹​）​中​创​建​文​件​时​不​会​自​动​应​用​模​板
				 */
				desc: string
			}
			folderTemplates: {
				/**
				 * 模​板​配​置
				 */
				name: string
				desc: string
			}
		}
		quick_path: {
			/**
			 * 快​速​路​径
			 */
			name: string
			/**
			 * 快​速​获​取​指​定​文​件​/​文​件​夹​的​路​径
			 */
			desc: string
			addEditorMenu: {
				/**
				 * 添​加​编​辑​器​菜​单
				 */
				name: string
				/**
				 * 在​编​辑​器​菜​单​中​添​加​粘​贴​当​前​文​件​路​径​的​选​项
				 */
				desc: string
			}
			addFileMenu: {
				/**
				 * 添​加​文​件​列​表​菜​单
				 */
				name: string
				/**
				 * 在​文​件​列​表​菜​单​中​添​加​复​制​文​件​/​文​件​夹​路​径​的​选​项
				 */
				desc: string
			}
			useAbsolutePath: {
				/**
				 * 绝​对​路​径
				 */
				name: string
				/**
				 * 使​用​绝​对​路​径​，​即​从​操​作​系​统​根​目​录​开​始​的​路​径
				 */
				desc: string
			}
			pathSeparator: {
				/**
				 * 分​隔​符
				 */
				name: string
				/**
				 * 多​个​路​径​的​分​隔​符
				 */
				desc: string
				/**
				 * 换​行
				 */
				newline: string
				/**
				 * 逗​号
				 */
				comma: string
				/**
				 * 分​号
				 */
				semicolon: string
				/**
				 * 空​格
				 */
				space: string
			}
		}
		table_calculator: {
			/**
			 * 表​格​计​算​器
			 */
			name: string
			/**
			 * 为​ ​m​a​r​k​d​o​w​n​ ​表​格​数​据​提​供​持​久​化​公​式​计​算
			 */
			desc: string
		}
	}
	command: {
		quick_path: {
			/**
			 * 复​制​当​前​文​件​路​径
			 */
			copy_current_file_path: string
			/**
			 * 复​制​当​前​目​录​路​径
			 */
			copy_current_folder_path: string
		}
	}
	menu: {
		quick_path: {
			/**
			 * 复​制​文​件​路​径
			 */
			copy_file_path: string
			/**
			 * 复​制​多​个​路​径
			 */
			copy_files_path: string
			/**
			 * 复​制​目​录​路​径
			 */
			copy_folder_path: string
			/**
			 * 粘​贴​当​前​文​件​路​径
			 */
			paste_current_file_path: string
			/**
			 * 粘​贴​当​前​目​录​路​径
			 */
			paste_current_folder_path: string
		}
	}
	notice: {
		quick_path: {
			/**
			 * 路​径​已​复​制​到​剪​贴​板
			 */
			copy_success: string
			/**
			 * 复​制​路​径​失​败
			 */
			copy_failure: string
			/**
			 * 当​前​文​件​位​于​根​目​录​，​无​法​获​取​上​级​文​件​夹​路​径
			 */
			root_path_warning: string
		}
	}
}

export type TranslationFunctions = {
	settings: {
		folder_templates: {
			/**
			 * 文件夹模板
			 */
			name: () => LocalizedString
			/**
			 * 在指定文件夹下创建新文件时，无感知应用模板
			 */
			desc: () => LocalizedString
			templatesFolderPath: {
				/**
				 * 模板文件夹位置
				 */
				name: () => LocalizedString
				/**
				 * 存放模板文件的文件夹, 默认与官方模板位置相同
				 */
				desc: () => LocalizedString
			}
			ignoredFolders: {
				/**
				 * 忽略文件夹
				 */
				name: () => LocalizedString
				/**
				 * 在这些文件夹（包括子文件夹）中创建文件时不会自动应用模板
				 */
				desc: () => LocalizedString
			}
			folderTemplates: {
				/**
				 * 模板配置
				 */
				name: () => LocalizedString
				desc: () => LocalizedString
			}
		}
		quick_path: {
			/**
			 * 快速路径
			 */
			name: () => LocalizedString
			/**
			 * 快速获取指定文件/文件夹的路径
			 */
			desc: () => LocalizedString
			addEditorMenu: {
				/**
				 * 添加编辑器菜单
				 */
				name: () => LocalizedString
				/**
				 * 在编辑器菜单中添加粘贴当前文件路径的选项
				 */
				desc: () => LocalizedString
			}
			addFileMenu: {
				/**
				 * 添加文件列表菜单
				 */
				name: () => LocalizedString
				/**
				 * 在文件列表菜单中添加复制文件/文件夹路径的选项
				 */
				desc: () => LocalizedString
			}
			useAbsolutePath: {
				/**
				 * 绝对路径
				 */
				name: () => LocalizedString
				/**
				 * 使用绝对路径，即从操作系统根目录开始的路径
				 */
				desc: () => LocalizedString
			}
			pathSeparator: {
				/**
				 * 分隔符
				 */
				name: () => LocalizedString
				/**
				 * 多个路径的分隔符
				 */
				desc: () => LocalizedString
				/**
				 * 换行
				 */
				newline: () => LocalizedString
				/**
				 * 逗号
				 */
				comma: () => LocalizedString
				/**
				 * 分号
				 */
				semicolon: () => LocalizedString
				/**
				 * 空格
				 */
				space: () => LocalizedString
			}
		}
		table_calculator: {
			/**
			 * 表格计算器
			 */
			name: () => LocalizedString
			/**
			 * 为 markdown 表格数据提供持久化公式计算
			 */
			desc: () => LocalizedString
		}
	}
	command: {
		quick_path: {
			/**
			 * 复制当前文件路径
			 */
			copy_current_file_path: () => LocalizedString
			/**
			 * 复制当前目录路径
			 */
			copy_current_folder_path: () => LocalizedString
		}
	}
	menu: {
		quick_path: {
			/**
			 * 复制文件路径
			 */
			copy_file_path: () => LocalizedString
			/**
			 * 复制多个路径
			 */
			copy_files_path: () => LocalizedString
			/**
			 * 复制目录路径
			 */
			copy_folder_path: () => LocalizedString
			/**
			 * 粘贴当前文件路径
			 */
			paste_current_file_path: () => LocalizedString
			/**
			 * 粘贴当前目录路径
			 */
			paste_current_folder_path: () => LocalizedString
		}
	}
	notice: {
		quick_path: {
			/**
			 * 路径已复制到剪贴板
			 */
			copy_success: () => LocalizedString
			/**
			 * 复制路径失败
			 */
			copy_failure: () => LocalizedString
			/**
			 * 当前文件位于根目录，无法获取上级文件夹路径
			 */
			root_path_warning: () => LocalizedString
		}
	}
}

export type Formatters = {}
