import esbuild from "esbuild";
import process from "process";
import postcss from "postcss";
import postcssNesting from "postcss-nesting";
import builtins from "builtin-modules";
import fs from "fs-extra";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const renamePlugin = () => ({
	name: "rename-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			const file = build.initialOptions.outfile;
			const parent = path.dirname(file);
			const cssFileName = path.join(parent, "main.css");
			const newCssFileName = path.join(parent, "styles.css");

			if (fs.existsSync(cssFileName)) {
				try {
					if (fs.existsSync(newCssFileName)) {
						fs.unlinkSync(newCssFileName);
					}
					fs.renameSync(cssFileName, newCssFileName);
				} catch (e) {
					console.error("Failed to rename CSS file:", e);
				}
			}
		});
	},
});

const cssReBuild = () => ({
	name: "css-rebuild",
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			try {
				const css = await fs.promises.readFile(args.path, "utf8");
				const result = await postcss([postcssNesting]).process(css, {
					from: args.path,
				});

				const outDir = path.dirname(build.initialOptions.outfile);
				if (!fs.existsSync(outDir)) {
					fs.mkdirSync(outDir, { recursive: true });
				}

				return {
					contents: result.css,
					loader: "css",
				};
			} catch (error) {
				console.error("Error processing CSS:", error);
				return {
					contents: "",
					loader: "css",
				};
			}
		});
	},
});

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [renamePlugin(), cssReBuild()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".ttf": "base64",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
