import builtins from "builtin-modules";
import esbuild from "esbuild";
import fs from "fs-extra";
import path from "node:path";
import process from "node:process";
import postcss from "postcss";
import postcssNesting from "postcss-nesting";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 参数解析：支持 dev 和 prod 两种模式
// 用法: node esbuild.config.mjs [dev|prod|production]
const args = process.argv.slice(2);
const mode = args[0] || "dev";
const prod = mode === "production" || mode === "prod";
const outDir = "dist";

/**
 * CSS 文件重命名插件
 * 在构建完成后，将 esbuild 生成的 main.css 重命名为 styles.css
 * @returns {Object} esbuild 插件对象
 */
const renamePlugin = () => ({
	name: "rename-plugin",
	setup(build) {
		build.onEnd(async () => {
			const src = path.join(outDir, "main.css");
			const dest = path.join(outDir, "styles.css");

			if (fs.existsSync(src)) {
				try {
					fs.moveSync(src, dest, { overwrite: true });
				} catch (error) {
					console.error("Failed to rename CSS file:", error);
				}
			}
		});
	},
});

/**
 * CSS 处理插件
 * 使用 PostCSS 和 postcss-nesting 插件处理 CSS 文件，支持 CSS 嵌套语法
 * 在构建过程中自动处理所有 .css 文件
 * @returns {Object} esbuild 插件对象
 */
const cssReBuild = () => ({
	name: "css-rebuild",

	setup(build) {
		// 注册一个加载器，用于处理所有 CSS 文件
		// filter 参数是一个正则表达式，匹配所有 .css 扩展名的文件
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			try {
				// 读取 CSS 文件内容
				// args.path 包含当前处理的 CSS 文件的完整路径
				const css = await fs.promises.readFile(args.path, "utf8");

				// 使用 PostCSS 处理 CSS 文件
				// postcssNesting 插件允许在 CSS 中使用嵌套语法（类似 SCSS）
				const result = await postcss([postcssNesting]).process(css, {
					from: args.path, // 指定源文件路径，用于生成正确的源映射
				});

				// 确保输出目录存在，如果不存在则创建
				fs.ensureDirSync(outDir);

				// 返回处理后的 CSS 内容
				// contents: 处理后的 CSS 代码
				// loader: 告诉 esbuild 如何解释这些内容（作为 CSS）
				return {
					contents: result.css,
					loader: "css",
				};
			} catch (error) {
				// 错误处理：如果 CSS 处理过程中出现任何错误
				console.error("Error processing CSS:", error);

				// 返回空内容，避免构建完全失败
				// 这样即使 CSS 处理失败，构建过程仍然可以继续
				return {
					contents: "",
					loader: "css",
				};
			}
		});
	},
});

// 复制 manifest.json 到输出目录
function copyManifest() {
	// 确保输出目录存在，如果不存在则创建
	fs.ensureDirSync(outDir);

	const src = path.join(process.cwd(), "manifest.json");
	const dest = path.join(process.cwd(), outDir, "manifest.json");
	try {
		fs.copyFileSync(src, dest);
		console.log("✓ 已复制 manifest.json 到 dist 目录");
	} catch (e) {
		console.error("⚠ 复制 manifest.json 失败:", e.message);
	}
}

// 监听 manifest.json 变化（带防抖和内容比较，避免重复触发）
function watchManifest() {
	const manifestPath = path.join(process.cwd(), "manifest.json");

	if (!fs.existsSync(manifestPath)) {
		return;
	}

	let copyTimer = null;
	let lastContent = fs.readFileSync(manifestPath, "utf8");

	fs.watch(manifestPath, (eventType) => {
		if (eventType === "change") {
			// 防抖：延迟 100ms 执行，避免短时间内多次触发
			if (copyTimer) {
				clearTimeout(copyTimer);
			}
			copyTimer = setTimeout(() => {
				try {
					const newContent = fs.readFileSync(manifestPath, "utf8");
					// 只有内容真正改变时才复制
					if (newContent !== lastContent) {
						lastContent = newContent;
						copyManifest();
					}
				} catch (e) {
					console.error("⚠ 读取 manifest.json 失败:", e.message);
				}
				copyTimer = null;
			}, 100);
		}
	});
}

// 创建 esbuild context
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [renamePlugin(), cssReBuild()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outDir,
	minify: prod,
	drop: prod ? ["console"] : [],
	loader: {
		".ttf": "base64",
	},
});

// 初始构建时复制 manifest.json
copyManifest();

if (prod) {
	// 生产模式：构建一次后退出
	await context.rebuild();
	console.log("✅ 生产构建完成");
	process.exit(0);
} else {
	// 开发模式：监听文件变化
	console.log("👀 开发模式启动，监听文件变化...");
	watchManifest();
	await context.watch();
}
